services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data


volumes:
  redis-data:
    driver: local
